central:
  reports:
    datastores:
      - artifact://nao1215/leadtime
      - artifact://nao1215/jose
      # - artifact://owner/repo
      # - artifact://owner/other-repo
      # - artifact://owner/another-repo
  badges:
    datastores:
      - local://badges
  push:
    enable: true
