central:
  reports:
    datastores:
      - artifact://nao1215/gup
      - artifact://nao1215/denv
      - artifact://nao1215/leadtime
      - artifact://nao1215/jose
      - artifact://nao1215/aiondb
      - artifact://nao1215/imaging
      - artifact://nao1215/emigre
      - artifact://nao1215/spare
      - artifact://nao1215/spectest
      - artifact://nao1215/pooh
      - artifact://nao1215/hottest
      - artifact://nao1215/rainbow
      - artifact://nao1215/spectest
      - artifact://nao1215/mermaid
      - artifact://nao1215/markdown
      - artifact://nao1215/diff
      - artifact://nao1215/imaging
      - artifact://nao1215/sqly
      - artifact://nao1215/hasher
      - artifact://nao1215/csv
      - artifact://nao1215/honeycomb
      - artifact://nao1215/coincheck
      - artifact://nao1215/hurrah
      - artifact://nao1215/vogen
      - artifact://nao1215/sqluv
      - artifact://nao1215/filesql
      # - artifact://owner/repo
      # - artifact://owner/other-repo
      # - artifact://owner/another-repo
  badges:
    datastores:
      - local://badges
  push:
    enable: true
