central:
  reports:
    datastores:
      - artifact://nao1215/gup
      - artifact://nao1215/denv
      - artifact://nao1215/leadtime
      - artifact://nao1215/jose
      - artifact://nao1215/aiondb
      - artifact://nao1215/imaging
      - artifact://nao1215/emigre
      - artifact://nao1215/spare
      # - artifact://owner/repo
      # - artifact://owner/other-repo
      # - artifact://owner/another-repo
  badges:
    datastores:
      - local://badges
  push:
    enable: true
